type Language = 'en' | 'ru';

export const translations = {
  en: {
    noRecordsFound: "No records found.",
    postedBy: "Posted by",
    filterByCategory: "Filter by category:",
    all: "All",
    search: "Search...",
    sortResults: "Sort results:",
    relevance: "Relevance",
    dateOldest: "Date (Oldest)",
    uponRequest: "Upon request",
    free: "Free",
    'my items': 'My Items',
    'my services': 'My Services',
    'my events': 'My Events',
    viewInChat: "Open in Chat",
    contactAuthor: "Contact Author",
    price: 'Price',
    currency: 'Currency',
    delete: 'Delete',
    deleteConfirmation: 'Are you sure you want to delete this item?',
    interestedInItemMessage: "Hello, I'm interested in your item: ",
    interestedInServiceMessage: "Hello, I'm interested in your service: ",
    interestedInEventMessage: "Hello, I'm interested in the event: ",
    interestedInNewsMessage: "Hello, I'm writing to you about the news: ",
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
  },
  ru: {
    noRecordsFound: "Записей не найдено.",
    postedBy: "Автор",
    filterByCategory: "Фильтр по категории:",
    all: "Все",
    search: "Поиск...",
    sortResults: "Сортировка результатов:",
    relevance: "Релевантность",
    dateOldest: "Дата (Старые)",
    uponRequest: "По запросу",
    free: "Бесплатно",
    'my items': 'Мои товары',
    'my services': 'Мои услуги',
    'my events': 'Мои события',
    viewInChat: "Открыть в чате",
    contactAuthor: "Связаться с автором",
    price: 'Цена',
    currency: 'Валюта',
    delete: 'Удалить',
    deleteConfirmation: 'Вы уверены, что хотите удалить этот элемент?',
    interestedInItemMessage: 'Здравствуйте, пишу на счет вашего объявления: ',
    interestedInServiceMessage: 'Здравствуйте, меня интересует услуга: ',
    interestedInEventMessage: 'Здравствуйте, пишу на счет события: ',
    interestedInNewsMessage: 'Здравствуйте, пишу на счет новости: ',
    cancel: 'Отменить',
    save: 'Сохранить',
    edit: 'Редактировать',
  },
};

export function getTranslation(key: keyof typeof translations.en, language: Language): string {
  return translations[language][key] || translations.en[key];
}