type Language = 'en' | 'ru';

export const translations = {
  en: {
    noRecordsFound: "No records found.",
    postedBy: "Posted by",
    filterByCategory: "Filter by category:",
    all: "All",
    search: "Search...",
    sortResults: "Sort results:",
    relevance: "Relevance",
    dateOldest: "Date (Oldest)",
    uponRequest: "Upon request",
    free: "Free",
    'my items': 'My Items',
    'my services': 'My Services',
    'my events': 'My Events',
    viewInChat: "Open in Chat",
    contactAuthor: "Contact Author",
    price: 'Price',
    currency: 'Currency',
    delete: 'Delete',
    deleteConfirmation: 'Are you sure you want to delete this item?',
    interestedInItemMessage: "Hello, I'm interested in your item: ",
    interestedInServiceMessage: "Hello, I'm interested in your service: ",
    interestedInEventMessage: "Hello, I'm interested in the event: ",
    interestedInNewsMessage: "Hello, I'm writing to you about the news: ",
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    title: 'Title',
    date: 'Date',
    description: 'Description',
    communitySetup: 'Community Setup',
    selectLanguage: 'Select Language',
    enterLocation: 'Enter Location',
    pickLocation: 'Pick Location',
    enterDescription: 'Enter Description',
    english: 'English',
    russian: 'Russian',
    location: 'Location',
    back: 'Back',
    next: 'Next',
    finish: 'Finish',
    confirm: 'Confirm',
    selectedLocation: "Selected location",
    clickMapToSelectLocation: "Click on the map to select a location",
    ongoingSetup: "is being setup. Please check later.",
    entityExtractionSettings: 'Hashtag Settings',
    eventHashtag: 'Event Hashtag',
    itemHashtag: 'Item Hashtag',
    serviceHashtag: 'Service Hashtag',
    newsHashtag: 'News Hashtag',
    event: 'event',
    item: 'item',
    service: 'service',
    news: 'news',
    createNewEntityInstructionPart1: 'To create a new {{entityType}}, send a message with the following hashtag:',
    createNewEntityInstructionPart2: 'in the community chat.',
    noEventsFound: 'No events found',
    noItemsFound: 'No items found',
    noServicesFound: 'No services found',
    noNewsFound: 'No news found',
  },
  ru: {
    noRecordsFound: "Записей не найдено.",
    postedBy: "Автор",
    filterByCategory: "Фильтр по категории:",
    all: "Все",
    search: "Поиск...",
    sortResults: "Сортировка результатов:",
    relevance: "Релевантность",
    dateOldest: "Дата (Старые)",
    uponRequest: "По запросу",
    free: "Бесплатно",
    'my items': 'Мои товары',
    'my services': 'Мои услуги',
    'my events': 'Мои события',
    viewInChat: "Открыть в чате",
    contactAuthor: "Связаться с автором",
    price: 'Цена',
    currency: 'Валюта',
    delete: 'Удалить',
    deleteConfirmation: 'Вы уверены, что хотите удалить этот элемент?',
    interestedInItemMessage: 'Здравствуйте, пишу на счет вашего объявления: ',
    interestedInServiceMessage: 'Здравствуйте, меня интересует услуга: ',
    interestedInEventMessage: 'Здравствуйте, пишу на счет события: ',
    interestedInNewsMessage: 'Здравствуйте, пишу на счет новости: ',
    cancel: 'Отменить',
    save: 'Сохранить',
    edit: 'Редактировать',
    title: 'Название',
    date: 'Дата',
    description: 'Описание',
    communitySetup: 'Настройка сообщества',
    selectLanguage: 'Выберите язык',
    enterLocation: 'Введите местоположение',
    pickLocation: 'Выбрать местоположение',
    enterDescription: 'Введите описание',
    english: 'Английский',
    russian: 'Русский',
    location: 'Местоположение',
    back: 'Назад',
    next: 'Далее',
    finish: 'Завершить',
    confirm: 'Подтвердить',
    selectedLocation: "Выбранное местоположение",
    clickMapToSelectLocation: "Нажмите на карту, чтобы выбрать местоположение",
    ongoingSetup: "настраивается. Пожалуйста, попробуйте зайти позже.",
    entityExtractionSettings: 'Настройка хэштегов',
    eventHashtag: 'Хештег события',
    itemHashtag: 'Хештег товара',
    serviceHashtag: 'Хештег услуги',
    newsHashtag: 'Хештег новости',
    event: 'мероприятие',
    item: 'товар',
    service: 'услугу',
    news: 'новость',
    noEventsFound: 'Нет опубликованных событий',
    noItemsFound: 'Нет опубликованных товаров',
    noServicesFound: 'Нет опубликованных услуг',
    noNewsFound: 'Нет опубликованных новостей',
    createNewEntityInstructionPart1: 'Чтобы добавить {{entityType}}, отправьте сообщение c хэштегом:',
    createNewEntityInstructionPart2: 'в чат сообщества.',
  },
};

export function getTranslation(key: keyof typeof translations.en, language: Language): string {
  return translations[language][key] || translations.en[key];
}